Fix tab component find for ActionPreview
alexkuz/redux-devtools-inspector pull request #56
Opened 2016-11-25 22:18 UTC by jhen0409

Fixes the error `Uncaught TypeError: Cannot read property 'component' of undefined`.

2016-11-26 11:54 UTC, zalmoxisus commented
It shouldn't happen, because [we're preventing the first rendering till the monitor reducer gets invoked](https://github.com/zalmoxisus/remotedev-app/blob/master/src/app/containers/DevTools.js#L57-L60). Could you please provide steps to reproduce?

Of course, merging this PR will help to avoid that workaround, but the same problem will be for Chart Monitor and for other monitors as well. Monitor's authors expect the reducer to be called with default values before rendering the component, but, in case of the extension, we need first to render the component before being able to call the reducer (to call `DevtoolsInspector.update`).

2016-11-26 22:30 UTC, jhen0409 commented
A reason is I used `redux-persist`, and it persist the older monitorState (No `tabName`), so this error will thrown when `persist/REHYDRATE` dispatched.

2017-01-04 11:05 UTC, zalmoxisus requested changes

2017-01-04 11:05 UTC, zalmoxisus commented on src/ActionPreview.jsx
> +    tabName: 'Action'
Shouldn't it be `Diff` like in [default state](https://github.com/alexkuz/redux-devtools-inspector/blob/master/src/redux.js#L8)?

2017-01-04 13:42 UTC, jhen0409 commented on src/ActionPreview.jsx
> +    tabName: 'Action'
Ahh you're right, It's fixed.

2017-01-04 13:48 UTC, zalmoxisus approved these changes

2017-01-08 18:32 UTC, merged