Support for Symbols in action types
alexkuz/redux-devtools-inspector pull request #63
Opened 2017-01-04 11:27 UTC by zalmoxisus

It just reimplements https://github.com/gaearon/redux-devtools-log-monitor/pull/29 and also supports `null` as action type per https://github.com/gaearon/redux-devtools-log-monitor/pull/55.

There's still an error in the demo, coming from `redux-logger`, as it doesn't support symbols.

2017-01-08 18:44 UTC, alexkuz requested changes

2017-01-08 18:44 UTC, alexkuz commented on demo/src/js/DemoApp.jsx
> +    addSymbol: () => ({ type: Symbol('ADD_SYMBOL') }),
Please add `window.` here - just to make eslint happy

2017-01-08 18:44 UTC, alexkuz commented on demo/src/js/reducers.js
> +  addSymbol: (state=null, action) => action.type === Symbol('ADD_SYMBOL') ?
here too

2017-01-08 18:44 UTC, alexkuz commented on src/ActionListRow.jsx
> +          {action.type !== null && action.type.toString()}
I suggest something like this:
```js
action.type === null ?
  '<NULL>' :
  (action.type.toString() || '<EMPTY>')
```

2017-01-08 19:16 UTC, zalmoxisus commented on src/ActionListRow.jsx
> +          {action.type !== null && action.type.toString()}
That's great. Will change now. Thanks for the review!

2017-01-28 14:25 UTC, zalmoxisus commented
Even though Redux warns when having `undefined` as action type, we should still check it here, to avoid unexpected exceptions. For example, when persisting the state a symbol will be added to localStorage as `undefined` because `JSON.stringify({ type: Symbol('BECOMES_UNDEFINED') }) === '{}'`. It can be prevented with https://github.com/zalmoxisus/redux-devtools-instrument/pull/14, but the parameter is optional and there could be other cases.

2017-01-31 21:04 UTC, merged